var pttBoardList = [
	['AllTogether','[歐兔] 終結單身的好所在','http://www.ptt.cc/bbs/AllTogether/index.html'],
	['AKB48','愛與正義的AKB48','http://www.ptt.cc/bbs/AKB48/index.html'],
	['Android','[安卓] 你不需要懂手機，你需要手機懂…','http://www.ptt.cc/bbs/Android/index.html'],
	['AndroidDev','[AndroidDev] 開發者們，歡迎光臨','http://www.ptt.cc/bbs/AndroidDev/index.html'],
	['AntiVirus','[防毒] 請注意!  原PO沒回=結案','http://www.ptt.cc/bbs/AntiVirus/index.html'],
	['Aquarium','水族板','http://www.ptt.cc/bbs/Aquarium/index.html'],
	['Aquarius','水瓶座','http://www.ptt.cc/bbs/Aquarius/index.html'],
	['Aries','牡羊板','http://www.ptt.cc/bbs/Aries/index.html'],
	['Ask','問板','http://www.ptt.cc/bbs/Ask/index.html'],
	['AYA','妖墨紡','http://www.ptt.cc/bbs/AYA/index.html'],
	['BabyMother','媽寶板','http://www.ptt.cc/bbs/BabyMother/index.html'],
	['Baseball','[棒球]','http://www.ptt.cc/bbs/Baseball/index.html'],
	['Beauty','[表特] 帥哥美女板','http://www.ptt.cc/bbs/Beauty/index.html'],
	['BeautySalon','[美保] 加強保濕,拒當白屑公主','http://www.ptt.cc/bbs/BeautySalon/index.html'],
	['BoardGame','歡樂桌上遊戲板','http://www.ptt.cc/bbs/BoardGame/index.html'],
	['Book11','不可詩意','http://www.ptt.cc/bbs/Book11/index.html'],
	['Boom','爆','http://www.ptt.cc/bbs/Boom/index.html'],
	['Boy-Girl','男女交往｜祝天下的媽媽們母親節快樂！','http://www.ptt.cc/bbs/Boy-Girl/index.html'],
	['broadcasting','實況板','http://www.ptt.cc/bbs/broadcasting/index.html'],
	['BusyXD','열심히하자','http://www.ptt.cc/bbs/BusyXD/index.html'],
	['but','but, or bug...','http://www.ptt.cc/bbs/but/index.html'],
	['BuyTogether','合購板','http://www.ptt.cc/bbs/BuyTogether/index.html'],
	['C-Clown','Crown們正在動搖','http://www.ptt.cc/bbs/C-Clown/index.html'],
	['C_Chat','[希洽] 希洽孃的埋藏金','http://www.ptt.cc/bbs/C_Chat/index.html'],
	['Cancer','巨蟹座','http://www.ptt.cc/bbs/Cancer/index.html'],
	['Capricornus','魔羯座','http://www.ptt.cc/bbs/Capricornus/index.html'],
	['Car','[四輪] 汽車總動員','http://www.ptt.cc/bbs/Car/index.html'],
	['CARDS_COLLECTION','卡片收藏交流','http://www.ptt.cc/bbs/CARDS_COLLECTION/index.html'],
	['CareerPlan','生涯規畫板','http://www.ptt.cc/bbs/CareerPlan/index.html'],
	['cat','[貓板] ～～～','http://www.ptt.cc/bbs/cat/index.html'],
	['cat_talk','聽妮可隨便說說，隨便走走。','http://www.ptt.cc/bbs/cat_talk/index.html'],
	['CestKaedely','大黃楓進行曲','http://www.ptt.cc/bbs/CestKaedely/index.html'],
	['chacha_cat','天橋下說書妹','http://www.ptt.cc/bbs/chacha_cat/index.html'],
	['ChemMen','一包的個人板','http://www.ptt.cc/bbs/ChemMen/index.html'],
	['Chiayi','嘉義板','http://www.ptt.cc/bbs/Chiayi/index.html'],
	['chin','夕陽的個版','http://www.ptt.cc/bbs/chin/index.html'],
	['China','中國研究板','http://www.ptt.cc/bbs/China/index.html'],
	['ChinaDrama','大陸影劇板','http://www.ptt.cc/bbs/ChinaDrama/index.html'],
	['ChocolateBoy','無可救藥的喜歡','http://www.ptt.cc/bbs/ChocolateBoy/index.html'],
	['Christianity','吉利支丹','http://www.ptt.cc/bbs/Christianity/index.html'],
	['CityNight','CityNight','http://www.ptt.cc/bbs/CityNight/index.html'],
	['coffee_shop','在無限暴風雨中追尋人生樂趣','http://www.ptt.cc/bbs/coffee_shop/index.html'],
	['comsboy','不期不待ACG雜談日記','http://www.ptt.cc/bbs/comsboy/index.html'],
	['conviction','EARTH AIR WATER FIRE','http://www.ptt.cc/bbs/conviction/index.html'],
	['CookyCat','我是CookyCat 我反黑箱服貿','http://www.ptt.cc/bbs/CookyCat/index.html'],
	['CPLife','省錢生活 - 轉文請寄 cplife.b@disp.cc','http://www.ptt.cc/bbs/CPLife/index.html'],
	['crosslegs','捻鬍鬚','http://www.ptt.cc/bbs/crosslegs/index.html'],
	['cukebox','黃瓜個人板','http://www.ptt.cc/bbs/cukebox/index.html'],
	['cuteween','無限FLY HIGH','http://www.ptt.cc/bbs/cuteween/index.html'],
	['Daniel','阿丹的個板','http://www.ptt.cc/bbs/Daniel/index.html'],
	['DC','數位相機板','http://www.ptt.cc/bbs/DC/index.html'],
	['debate','辯論','http://www.ptt.cc/bbs/debate/index.html'],
	['DIABLO','[暗黑] 暗黑破壞神','http://www.ptt.cc/bbs/DIABLO/index.html'],
	['DietDiary','減肥日記','http://www.ptt.cc/bbs/DietDiary/index.html'],
	['dog','[狗板]','http://www.ptt.cc/bbs/dog/index.html'],
	['Doraemon','[叮噹] ドラえもん的百寶袋','http://www.ptt.cc/bbs/Doraemon/index.html'],
	['DotA2','DotA2','http://www.ptt.cc/bbs/DotA2/index.html'],
	['DYU','大葉大學','http://www.ptt.cc/bbs/DYU/index.html'],
	['e-shopping','網路購物','http://www.ptt.cc/bbs/e-shopping/index.html'],
	['EAseries','歐美影集板','http://www.ptt.cc/bbs/EAseries/index.html'],
	['EZsoft','[軟體] 小軟體板','http://www.ptt.cc/bbs/EZsoft/index.html'],
	['Facebook','[臉書] 擁抱世界的 Facebook','http://www.ptt.cc/bbs/Facebook/index.html'],
	['FCBarcelona','巴塞隆納足球俱樂部','http://www.ptt.cc/bbs/FCBarcelona/index.html'],
	['Fitness','體適能 健康是唯一的標準','http://www.ptt.cc/bbs/Fitness/index.html'],
	['Food','美食板','http://www.ptt.cc/bbs/Food/index.html'],
	['Gay','男同志板','http://www.ptt.cc/bbs/Gay/index.html'],
	['Gemini','雙子座','http://www.ptt.cc/bbs/Gemini/index.html'],
	['GetMarry','結婚板-天氣好是拍婚紗好時機','http://www.ptt.cc/bbs/GetMarry/index.html'],
	['Google','Goooooooooogle 估狗版','http://www.ptt.cc/bbs/Google/index.html'],
	['Gosan',' ','http://www.ptt.cc/bbs/Gosan/index.html'],
	['Gossiping','[八卦] 天佑台灣','http://www.ptt.cc/bbs/Gossiping/index.html'],
	['GunsRushOnline','楓之谷Online','http://www.ptt.cc/bbs/GunsRushOnline/index.html'],
	['Hachi','藍白世界','http://www.ptt.cc/bbs/Hachi/index.html'],
	['hairdo','美髮板','http://www.ptt.cc/bbs/hairdo/index.html'],
	['Hamburger','漢堡哥Online','http://www.ptt.cc/bbs/Hamburger/index.html'],
	['HanGeng','[韓庚] All about HanGeng','http://www.ptt.cc/bbs/HanGeng/index.html'],
	['Haruhi','[SOS] 涼宮春日の看板','http://www.ptt.cc/bbs/Haruhi/index.html'],
	['Hate','黑特板','http://www.ptt.cc/bbs/Hate/index.html'],
	['HatePolitics','政治黑特板','http://www.ptt.cc/bbs/HatePolitics/index.html'],
	['HC_Guitar','新北市新莊區 HC吉他團練社','http://www.ptt.cc/bbs/HC_Guitar/index.html'],
	['Hearthstone','[爐石] 放狗2費→3費','http://www.ptt.cc/bbs/Hearthstone/index.html'],
	['HelloVenus','以朋友而名的家庭 HEL-LOVE-NUS','http://www.ptt.cc/bbs/HelloVenus/index.html'],
	['Helluin','Helluin','http://www.ptt.cc/bbs/Helluin/index.html'],
	['HKDay','香港地','http://www.ptt.cc/bbs/HKDay/index.html'],
	['hoar','高級別墅區','http://www.ptt.cc/bbs/hoar/index.html'],
	['home-sale','房屋買賣版','http://www.ptt.cc/bbs/home-sale/index.html'],
	['HomeTeach','家教板','http://www.ptt.cc/bbs/HomeTeach/index.html'],
	['HoneyBunny','光州和公州的相遇','http://www.ptt.cc/bbs/HoneyBunny/index.html'],
	['HorseRun','馬兒跑','http://www.ptt.cc/bbs/HorseRun/index.html'],
	['Howar31','[歐人] Howar31的Disp個人板！','http://www.ptt.cc/bbs/Howar31/index.html'],
	['Hsinchu','新竹板','http://www.ptt.cc/bbs/Hsinchu/index.html'],
	['IGuanTao','一貫道','http://www.ptt.cc/bbs/IGuanTao/index.html'],
	['Ingress','映‧詭‧思◎你今天，Ingress了嗎？','http://www.ptt.cc/bbs/Ingress/index.html'],
	['Instrument','Saxophone 薩克斯風板','http://www.ptt.cc/bbs/Instrument/index.html'],
	['Isayama','進擊的巨人','http://www.ptt.cc/bbs/Isayama/index.html'],
	['JapanDrama','日劇','http://www.ptt.cc/bbs/JapanDrama/index.html'],
	['Japan_Travel','希望能夠帶母親去日本玩','http://www.ptt.cc/bbs/Japan_Travel/index.html'],
	['Joke','[就可]','http://www.ptt.cc/bbs/Joke/index.html'],
	['job','!!工時兩周超過84h 一定要加班費!','http://www.ptt.cc/bbs/job/index.html'],
	['iPhone','[iOS] iTools強  案件發生','http://www.ptt.cc/bbs/iPhone/index.html'],
	['iPod','[iPod] Touch5 活過來吧iPod','http://www.ptt.cc/bbs/iPod/index.html'],
	['Kaohsiung','[高雄] 海洋首都 - Marine Kaohsiung','http://www.ptt.cc/bbs/Kaohsiung/index.html'],
	['kawaii','可愛板','http://www.ptt.cc/bbs/kawaii/index.html'],
	['Kells','阿詩鈴迷霧森林','http://www.ptt.cc/bbs/Kells/index.html'],
	['Key_Mou_Pad','[鍵鼠]賣鍵盤要附拔鍵器','http://www.ptt.cc/bbs/Key_Mou_Pad/index.html'],
	['Keroro0929','阿宅的KPOP小窩...&amp; other','http://www.ptt.cc/bbs/Keroro0929/index.html'],
	['kinomoto','一瞬の風になれ(轉瞬為風)','http://www.ptt.cc/bbs/kinomoto/index.html'],
	['kitsuneya','狐狸屋','http://www.ptt.cc/bbs/kitsuneya/index.html'],
	['Knuckles_note','那克斯的學習筆記','http://www.ptt.cc/bbs/Knuckles_note/index.html'],
	['KoreaDrama','韓劇 韓綜 韓星 討論版','http://www.ptt.cc/bbs/KoreaDrama/index.html'],
	['kpopminelook','韓流團體小說','http://www.ptt.cc/bbs/kpopminelook/index.html'],
	['KR_Entertain','[韓綜] 有沒有一首歌會讓你想起它','http://www.ptt.cc/bbs/KR_Entertain/index.html'],
	['KRCSF','閃耀世界','http://www.ptt.cc/bbs/KRCSF/index.html'],
	['kumakichi','熊窩','http://www.ptt.cc/bbs/kumakichi/index.html'],
	['Kurosaki','Kurosaki','http://www.ptt.cc/bbs/Kurosaki/index.html'],
	['L0','雖然富奸不是好事，但PDE真的很難......','http://www.ptt.cc/bbs/L0/index.html'],
	['Lamaxman','駝男嚴選','http://www.ptt.cc/bbs/Lamaxman/index.html'],
	['legendary','不管你信不信，反正我是信了...','http://www.ptt.cc/bbs/legendary/index.html'],
	['Leo','獅子座','http://www.ptt.cc/bbs/Leo/index.html'],
	['Lesbian','拉子板','http://www.ptt.cc/bbs/Lesbian/index.html'],
	['LetItSnow','世界で一番小さな海よ','http://www.ptt.cc/bbs/LetItSnow/index.html'],
	['Libra','天秤座','http://www.ptt.cc/bbs/Libra/index.html'],
	['Lifeismoney','[省錢]','http://www.ptt.cc/bbs/Lifeismoney/index.html'],
	['lingsk','境亭','http://www.ptt.cc/bbs/lingsk/index.html'],
	['Little-Games','小遊戲板~誠徵板主中','http://www.ptt.cc/bbs/Little-Games/index.html'],
	['LIVE','LIVE板-','http://www.ptt.cc/bbs/LIVE/index.html'],
	['LinuxDev','Linux程式開發:請先RTFM+STFW','http://www.ptt.cc/bbs/LinuxDev/index.html'],
	['Linux','[Linux] 小企鵝板','http://www.ptt.cc/bbs/LinuxDev/index.html'],
	['LoL','[英聯] 英雄聯盟 - 提摩必須死','http://www.ptt.cc/bbs/LoL/index.html'],
	['LoveAKG','隨想隨記','http://www.ptt.cc/bbs/LoveAKG/index.html'],
	['lovegg','蘋果蕃茄綠','http://www.ptt.cc/bbs/lovegg/index.html'],
	['LoveWorld','愛的世界','http://www.ptt.cc/bbs/LoveWorld/index.html'],
	['Love_Like_Dope','順著自己的心吧 結果如何就算了(欸','http://www.ptt.cc/bbs/Love_Like_Dope/index.html'],
	['LUCKY7','777','http://www.ptt.cc/bbs/LUCKY7/index.html'],
	['Lusttin','樂思亭 - 網路543的備份','http://www.ptt.cc/bbs/Lusttin/index.html'],
	['Mabinogi','新瑪奇','http://www.ptt.cc/bbs/Mabinogi/index.html'],
	['MacDev','Mac程式開發 沙箱可以，不要黑箱','http://www.ptt.cc/bbs/MacDev/index.html'],
	['Madoka','魔法少女小圓☆魔力 /人◕‿‿◕人\\ ','http://www.ptt.cc/bbs/Madoka/index.html'],
	['Magic','默默躲在第二頁的魔術格','http://www.ptt.cc/bbs/Magic/index.html'],
	['mail1130','妹兒依依三十','http://www.ptt.cc/bbs/mail1130/index.html'],
	['Manic','沒力客的個人版','http://www.ptt.cc/bbs/Manic/index.html'],
	['MapleStory-Online','新楓之谷Online','http://www.ptt.cc/bbs/MapleStory-Online/index.html'],
	['MakeUp','[美妝] 好特賣，衝了嗎？','http://www.ptt.cc/bbs/MakeUp/index.html'],
	['marriage','婚姻生活｜祝天下的媽媽們母親節快樂！','http://www.ptt.cc/bbs/marriage/index.html'],
	['Marvel','[DISP飄版] 有臉書粉絲專頁了！','http://www.ptt.cc/bbs/Marvel/index.html'],
	['MathThinking','數學思維的發展與應用','http://www.ptt.cc/bbs/MathThinking/index.html'],
	['Mayday','五月天專屬討論版','http://www.ptt.cc/bbs/Mayday/index.html'],
	['MBA','MBA申請討論板','http://www.ptt.cc/bbs/MBA/index.html'],
	['MD_info','麻豆資訊','http://www.ptt.cc/bbs/MD_info/index.html'],
	['memento','♡x206','http://www.ptt.cc/bbs/memento/index.html'],
	['MemorySea','記憶．海洋','http://www.ptt.cc/bbs/MemorySea/index.html'],
	['MenTalk','男人話題','http://www.ptt.cc/bbs/MenTalk/index.html'],
	['MeowCraft','當個創世貓 - 紙箱貓窩伺服器','http://www.ptt.cc/bbs/MeowCraft/index.html'],
	['MH','魔物獵人板','http://www.ptt.cc/bbs/MH/index.html'],
	['Miaoli','苗栗板','http://www.ptt.cc/bbs/Miaoli/index.html'],
	['mikelily','阿喵的窩','http://www.ptt.cc/bbs/mikelily/index.html'],
	['Militarylife','軍旅生活討論板','http://www.ptt.cc/bbs/Militarylife/index.html'],
	['milkfish','公開閱讀看板','http://www.ptt.cc/bbs/milkfish/index.html'],
	['MilyYang','楊格凌','http://www.ptt.cc/bbs/MilyYang/index.html'],
	['mind_game','大家來玩心理測驗~(≧▽≦)o[最近比較忙..…','http://www.ptt.cc/bbs/mind_game/index.html'],
	['Minecraft','當個創世神','http://www.ptt.cc/bbs/Minecraft/index.html'],
	['MiniFighter','迷你格鬥綜合遊戲板','http://www.ptt.cc/bbs/MiniFighter/index.html'],
	['Mist_forest','狸的謎境森林','http://www.ptt.cc/bbs/Mist_forest/index.html'],
	['MobileComm','行動通訊/手機板','http://www.ptt.cc/bbs/MobileComm/index.html'],
	['Modchip','改機板','http://www.ptt.cc/bbs/Modchip/index.html'],
	['Moment','快門按下的瞬間','http://www.ptt.cc/bbs/Moment/index.html'],
	['Movie','[電影]','http://www.ptt.cc/bbs/Movie/index.html'],
	['mud_3y','三國歪傳之降龍伏虎','http://www.ptt.cc/bbs/mud_3y/index.html'],
	['MyDeer','Deer my Bear (*・(エ)・)','http://www.ptt.cc/bbs/MyDeer/index.html'],
	['nadoka','秀吉我的嫁！','http://www.ptt.cc/bbs/nadoka/index.html'],
	['Nantou','[南投] 粉絲團 http://ppt.cc/fZSn','http://www.ptt.cc/bbs/Nantou/index.html'],
	['NashStyle','逐風','http://www.ptt.cc/bbs/NashStyle/index.html'],
	['NBA','美國職業籃球聯賽','http://www.ptt.cc/bbs/NBA/index.html'],
	['NBA_Film','[NBA_Film] NBA季後賽開打!!!!!!!','http://www.ptt.cc/bbs/NBA_Film/index.html'],
	['NCCU','國立政治大學','http://www.ptt.cc/bbs/NCCU/index.html'],
	['NCNU','國立暨南國際大學','http://www.ptt.cc/bbs/NCNU/index.html'],
	['NCTU','國立交通大學','http://www.ptt.cc/bbs/NCTU/index.html'],
	['NCU','國立中央大學','http://www.ptt.cc/bbs/NCU/index.html'],
	['ncuacg2','とある哲學の博麗神社','http://www.ptt.cc/bbs/ncuacg2/index.html'],
	['NDHU','國立東華大學','http://www.ptt.cc/bbs/NDHU/index.html'],
	['Neon','關心服貿之餘也不忘一天一養分','http://www.ptt.cc/bbs/Neon/index.html'],
	['Neverland','夢貓的彼端','http://www.ptt.cc/bbs/Neverland/index.html'],
	['NEWS','[新聞]','http://www.ptt.cc/bbs/NEWS/index.html'],
	['NewYork','紐約板','http://www.ptt.cc/bbs/NewYork/index.html'],
	['nightguest','深夜客','http://www.ptt.cc/bbs/nightguest/index.html'],
	['NinjaHarakiri','忍者切腹','http://www.ptt.cc/bbs/NinjaHarakiri/index.html'],
	['Nintendo','[任天堂] 2014 E3將發表新主機？','http://www.ptt.cc/bbs/Nintendo/index.html'],
	['note_of_book','殘篇斷簡','http://www.ptt.cc/bbs/note_of_book/index.html'],
	['novel','小說區怎麼都沒人!不要這邊鬧鬼阿~我會怕','http://www.ptt.cc/bbs/novel/index.html'],
	['noyarc','光速','http://www.ptt.cc/bbs/noyarc/index.html'],
	['NPUE','國立屏東教育大學','http://www.ptt.cc/bbs/NPUE/index.html'],
	['NSYSU','國立中山大學','http://www.ptt.cc/bbs/NSYSU/index.html'],
	['NTHU','國立清華大學','http://www.ptt.cc/bbs/NTHU/index.html'],
	['NTU','國立台灣大學','http://www.ptt.cc/bbs/NTU/index.html'],
	['NTUST','國立台灣科技大學','http://www.ptt.cc/bbs/NTUST/index.html'],
	['oguMYUN','金俊勉是打架王','http://www.ptt.cc/bbs/oguMYUN/index.html'],
	['OLdorm','SUPERSTAR K 12 3 4    5    ','http://www.ptt.cc/bbs/OLdorm/index.html'],
	['ONE_PIECE','海賊王','http://www.ptt.cc/bbs/ONE_PIECE/index.html'],
	['OnLineGame','線上遊戲討論板','http://www.ptt.cc/bbs/OnLineGame/index.html'],
	['Oversea_Job','海外工作版 誠徵面試心得','http://www.ptt.cc/bbs/Oversea_Job/index.html'],
	['Option','期貨與選擇權','http://www.ptt.cc/bbs/Option/index.html'],
	['ParkMinYoung','朴敏英．女神休息中','http://www.ptt.cc/bbs/ParkMinYoung/index.html'],
	['PC_Shopping','電腦消費討論','http://www.ptt.cc/bbs/PC_Shopping/index.html'],
	['perfectionplus','搬家諮詢','http://www.ptt.cc/bbs/perfectionplus/index.html'],
	['Perfume','日本女子電音團體','http://www.ptt.cc/bbs/Perfume/index.html'],
	['Philcat','Philcat的空間','http://www.ptt.cc/bbs/Philcat/index.html'],
	['PHP','PHP 程式語言','http://www.ptt.cc/bbs/PHP/index.html'],
	['Pisces','雙魚座','http://www.ptt.cc/bbs/Pisces/index.html'],
	['Players','再雷也可以笑','http://www.ptt.cc/bbs/Players/index.html'],
	['PlayStation','[iPS] PS系列主機專用討論版','http://www.ptt.cc/bbs/PlayStation/index.html'],
	['pphhxx2','小罐子','http://www.ptt.cc/bbs/pphhxx2/index.html'],
	['Precious_ONE','不如守著這場模糊情分','http://www.ptt.cc/bbs/Precious_ONE/index.html'],
	['Programming','程式設計版','http://www.ptt.cc/bbs/Programming/index.html'],
	['PttCard','PTT鄉民認同卡','http://www.ptt.cc/bbs/PttCard/index.html'],
	['PttFB','批踢踢FB官方粉絲團','http://www.ptt.cc/bbs/PttFB/index.html'],
	['PttHot','批踢踢熱門文章','http://www.ptt.cc/bbs/PttHot/index.html'],
	['PublicIssue','公民覺醒版 板旗投票中','http://www.ptt.cc/bbs/PublicIssue/index.html'],
	['PurpleLine','迷妹人生！','http://www.ptt.cc/bbs/PurpleLine/index.html'],
	['PuzzleDragon','[P&D] 法米通受賞&PAD BT推出紀念','http://www.ptt.cc/bbs/PuzzleDragon/index.html'],
	['P_chippclass','http://elemon.hangame.co.jp/','http://www.ptt.cc/bbs/P_chippclass/index.html'],
	['P_pig','雜亂豬窩','http://www.ptt.cc/bbs/P_pig/index.html'],
	['P_zenhow','推薦免費機率模擬與統計分析的電腦軟體','http://www.ptt.cc/bbs/P_zenhow/index.html'],
	['Rainlilt','秋山澪:雨ちん大好きです～❤','http://www.ptt.cc/bbs/Rainlilt/index.html'],
	['Raura','PTT文章收藏箱','http://www.ptt.cc/bbs/Raura/index.html'],
	['ray9751033','腦袋空空','http://www.ptt.cc/bbs/ray9751033/index.html'],
	['Redd','　　　　　　　　自我對話','http://www.ptt.cc/bbs/Redd/index.html'],
	['Regular_Pony_Time','探險活寶＆天兵公園＆彩虹小馬 分享俱…','http://www.ptt.cc/bbs/Regular_Pony_Time/index.html'],
	['River','[河流] Ｒｉｖｅｒ’ｓ　５４３','http://www.ptt.cc/bbs/River/index.html'],
	['Sagittarius','射手座','http://www.ptt.cc/bbs/Sagittarius/index.html'],
	['Salary','談薪不談心','http://www.ptt.cc/bbs/Salary/index.html'],
	['Science','自然科學板','http://www.ptt.cc/bbs/Science/index.html'],
	['Scorpio','天蠍座','http://www.ptt.cc/bbs/Scorpio/index.html'],
	['seiyuu','聲音魔法','http://www.ptt.cc/bbs/seiyuu/index.html'],
	['SHASHASHA','少女時代','http://www.ptt.cc/bbs/SHASHASHA/index.html'],
	['shobeat','不快不慢的生活','http://www.ptt.cc/bbs/shobeat/index.html'],
	['Simcity','beta快結束了哦','http://www.ptt.cc/bbs/Simcity/index.html'],
	['skate','溜冰板','http://www.ptt.cc/bbs/skate/index.html'],
	['skyruins','縱情中','http://www.ptt.cc/bbs/skyruins/index.html'],
	['SNSD','少時 Mr.Mr.!!!','http://www.ptt.cc/bbs/SNSD/index.html'],
	['Soft_Job','軟體業討論','http://www.ptt.cc/bbs/Soft_Job/index.html'],
	['StarCraft','星海爭霸','http://www.ptt.cc/bbs/StarCraft/index.html'],
	['Stock','股票板','http://www.ptt.cc/bbs/Stock/index.html'],
	['studyabroad','海外留學討論板','http://www.ptt.cc/bbs/studyabroad/index.html'],
	['StupidClown','你叫康2346?','http://www.ptt.cc/bbs/StupidClown/index.html'],
	['SuperJunior','Super Junior 슈퍼주니어','http://www.ptt.cc/bbs/SuperJunior/index.html'],
	['TableTennis','桌球','http://www.ptt.cc/bbs/TableTennis/index.html'],
	['Tainan','台南板','http://www.ptt.cc/bbs/Tainan/index.html'],
	['Taipei','台北板','http://www.ptt.cc/bbs/Taipei/index.html'],
	['TaiwanDrama','[台劇] 台劇板','http://www.ptt.cc/bbs/TaiwanDrama/index.html'],
	['Taoyuan','桃園板','http://www.ptt.cc/bbs/Taoyuan/index.html'],
	['Taurus','[金牛] 色大膽小被狗咬','http://www.ptt.cc/bbs/Taurus/index.html'],
	['Tech_Job','科技業甘苦談','http://www.ptt.cc/bbs/Tech_Job/index.html'],
	['Test','[測試] 測試板','http://www.ptt.cc/bbs/Test/index.html'],
	['Thai','泰語 ภาษาไทย','http://www.ptt.cc/bbs/Thai/index.html'],
	['Tias_Music','提亞斯音樂板','http://www.ptt.cc/bbs/Tias_Music/index.html'],
	['TL','[踢欸樓]ˊ_&gt;ˋ ','http://www.ptt.cc/bbs/TL/index.html'],
	['toast','吐司','http://www.ptt.cc/bbs/toast/index.html'],
	['togeda4ever','每天都在玩','http://www.ptt.cc/bbs/togeda4ever/index.html'],
	['Tomo','偷偷摸摸的Tomo','http://www.ptt.cc/bbs/Tomo/index.html'],
	['tomochin','偷摸','http://www.ptt.cc/bbs/tomochin/index.html'],
	['tonymoly','草莓很弱','http://www.ptt.cc/bbs/tonymoly/index.html'],
	['ToS','[神魔] 十抽條款/法海，是你？','http://www.ptt.cc/bbs/ToS/index.html'],
	['TOXYGIN','打掉重來','http://www.ptt.cc/bbs/TOXYGIN/index.html'],
	['TPPO','台灣製品促進組織','http://www.ptt.cc/bbs/TPPO/index.html'],
	['Traffic','高鐵開箱文','http://www.ptt.cc/bbs/Traffic/index.html'],
	['Transparent','                                ','http://www.ptt.cc/bbs/Transparent/index.html'],
	['traume','無料備份','http://www.ptt.cc/bbs/traume/index.html'],
	['TVXQ_JYJ','東方神起&amp;JYJ 神之胡蘿蔔','http://www.ptt.cc/bbs/TVXQ_JYJ/index.html'],
	['TyPhoon','颱風板','http://www.ptt.cc/bbs/TyPhoon/index.html'],
	['u12358','帳號.bbs@disp.cc','http://www.ptt.cc/bbs/u12358/index.html'],
	['ufobase','幽浮基地','http://www.ptt.cc/bbs/ufobase/index.html'],
	['vanbomme17','范博美的運動世界(笑)','http://www.ptt.cc/bbs/vanbomme17/index.html'],
	['Verivan','小角落畫圈圈','http://www.ptt.cc/bbs/Verivan/index.html'],
	['VideoShare','▂▃▄▆▇█《影 音 特 區》█▇▆▄▃▂','http://www.ptt.cc/bbs/VideoShare/index.html'],
	['Virgo','處女座','http://www.ptt.cc/bbs/Virgo/index.html'],
	['virsey','阿哈哈哈你看看你','http://www.ptt.cc/bbs/virsey/index.html'],
	['Volten','伏特恩','http://www.ptt.cc/bbs/Volten/index.html'],
	['walilecow','猛才能做大事','http://www.ptt.cc/bbs/walilecow/index.html'],
	['Wanted','[問安] m文＝違規，板規有更新！','http://www.ptt.cc/bbs/Wanted/index.html'],
	['Warcraft','魔獸爭霸三','http://www.ptt.cc/bbs/Warcraft/index.html'],
	['warrenchen','愛‧管閑‧事的 Junk Pile (ゴミじゃない)','http://www.ptt.cc/bbs/warrenchen/index.html'],
	['WawaMagic','娃娃の命理別館','http://www.ptt.cc/bbs/WawaMagic/index.html'],
	['wayne206','滷肉飯','http://www.ptt.cc/bbs/wayne206/index.html'],
	['Web_Design','網頁設計專版','http://www.ptt.cc/bbs/Web_Design/index.html'],
	['WhiteNovember','白色十一月團隊','http://www.ptt.cc/bbs/WhiteNovember/index.html'],
	['windyeddy','天音好毒板','http://www.ptt.cc/bbs/windyeddy/index.html'],
	['Windows','Windows 8 is out','http://www.ptt.cc/bbs/Windows/index.html'],
	['WindowsPhone','[WP] WP8.1 6月推送','http://www.ptt.cc/bbs/WindowsPhone/index.html'],
	['WomenTalk','女人話題','http://www.ptt.cc/bbs/WomenTalk/index.html'],
	['Wonderland','Wonderland','http://www.ptt.cc/bbs/Wonderland/index.html'],
	['WOW','魔獸世界','http://www.ptt.cc/bbs/WOW/index.html'],
	['XBOX','[XBOX]  XBOX ONE 2014年9月正式上市','http://www.ptt.cc/bbs/XBOX/index.html'],
	['YSisREAL','That\'s all.','http://www.ptt.cc/bbs/YSisREAL/index.html'],
	['yuelaobank','月老銀行單身新聞台','http://www.ptt.cc/bbs/yuelaobank/index.html'],
	['yumyun','馬路-我是國中生 但我知道立院廁所不會…','http://www.ptt.cc/bbs/yumyun/index.html'],
	['Yunlin','雲林板','http://www.ptt.cc/bbs/Yunlin/index.html'],
	['YZU','元智大學','http://www.ptt.cc/bbs/YZU/index.html'],
	['Zastrology','十二星座','http://www.ptt.cc/bbs/Zastrology/index.html']
];